title: cli-nerd.com
email: mail@damienklinnert.de
description: >
  Random thoughts on software engineering, functional programming and web development.
baseurl: ""
url: "http://cli-nerd.com"
author: Damien Klinnert
github_username:  damienklinnert

markdown: kramdown
#highlighter: pygments
