title: cli-nerd.com
email: mail@damienklinnert.de
description: >
  Thoughts on software engineering and functional programming.
baseurl: ""
url: "http://cli-nerd.com"
author: Damien Klinnert
github_username:  damienklinnert

markdown: kramdown
#highlighter: pygments
