title: cli-nerd.com
email: mail@damienklinnert.de
description: >
  Thoughts and concepts of software engineering for web development
baseurl: ""
url: "http://cli-nerd.com"
author: Damien Klinnert
twitter_username: damienklinnert
github_username:  damienklinnert

markdown: kramdown
highlighter: pygments