title: cli-nerd.com
email: mail@damienklinnert.de
description: >
  A blog about my insights into software development (the most valuable ones).
baseurl: "/cli-nerd.com"
url: "http://cli-nerd.com"
twitter_username: damienklinnert
github_username:  damienklinnert

markdown: kramdown
highlighter: pygments